// Code generated by mockery v2.26.1. DO NOT EDIT.

package txtest

import (
	context "context"

	txsql "github.com/sklyar/go-transact/txsql"
	mock "github.com/stretchr/testify/mock"
)

// DBHandler is an autogenerated mock type for the DBHandler type
type DBHandler struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, query, args
func (_m *DBHandler) Exec(ctx context.Context, query string, args ...interface{}) (txsql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 txsql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (txsql.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) txsql.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(txsql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Prepare provides a mock function with given fields: ctx, query
func (_m *DBHandler) Prepare(ctx context.Context, query string) (txsql.Stmt, error) {
	ret := _m.Called(ctx, query)

	var r0 txsql.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (txsql.Stmt, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) txsql.Stmt); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(txsql.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: ctx, query, args
func (_m *DBHandler) Query(ctx context.Context, query string, args ...interface{}) (txsql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 txsql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (txsql.Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) txsql.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(txsql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryRow provides a mock function with given fields: ctx, query, args
func (_m *DBHandler) QueryRow(ctx context.Context, query string, args ...interface{}) txsql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 txsql.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) txsql.Row); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(txsql.Row)
		}
	}

	return r0
}

type mockConstructorTestingTNewDBHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewDBHandler creates a new instance of DBHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDBHandler(t mockConstructorTestingTNewDBHandler) *DBHandler {
	mock := &DBHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
